### ISSUE TITLE
First draft

### ISSUE THREAD

**Issue by smpark7** [arfc/2019-park-global#2]
This issue is for the review of the first draft by @katyhuff.

[abstract.pdf](https://github.com/arfc/2019-park-global/files/2899117/abstract.pdf)

**Comment by katyhuff** [comment]
First pass comments.

Major Comment 1:

The focus of this paper is too far away from fuel cycle analysis (Global is a fuel cycle conference, and while there is an advanced reactor session, talks in that session should be focused on the fuel cycle aspects of those reactors at least in some way.). 

My tendency would be to state that, beyond this code-to-code validation, this talk should discuss, primarily, the impact of changing fuel composition on the safety parameters and the results of the transient simulations proposed (e.g. by running the simulations with cross sections generated based on beginning of life, early life, and equillibrium compositions).

Major Comment 2:
The first sentence of the third paragraph should be the first sentence of the abstract. It takes to long for the reader to see that this paper isn't about the design of moltres.

Minor comments:
- Well written, thank you.
- Please review the checklist.  Quite a lot of passive voice appears.
- Avoid "inputs"... instead use terminology like "input parameters"
- nuclear data library is too vague, be specific.
- The mesh is not coarse for more complex geometries. Adaptive meshing means that the mesh resolution changes during the simulation based on the physics. So, the mesh is not course for high gradients in the physics either. Moltres is not intended to be particularly low in computational resources (and one key aspect is that it and moose can scale for large complex meshes when run in parallel)
- I know this abstract must remain short, but too much time is spent talking about moltres and too little time is spent talking about the simulations you'll run and compare your results to. More detail about those simulations, less salesmanship of moltres.
- When is this due?

**Comment by smpark7** [comment]
Thank you for the review. I will do up the next draft by tomorrow, with the comments in mind. 

This is due on March 1, 11.59pm.
